version: '3.7'
services:
  ############################
  # Web app + Dapr sidecar
  ############################
  webapp:
    # Build is relative to the root directory where podman-compose is ran from
    build: ./app/backend
    ports:
      - "50002:50002"
    depends_on:
      - redis
      - placement
      - zipkin
      - dapr-dashboard
    environment:
      - DAPR_LOG_LEVEL=info
    networks:
      - demo-dapr-network
  webapp-dapr:
    image: "docker.io/daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "webapp",
      "--app-port", "3000",
      "--placement-host-address", "placement:50006",
      "--enable-profiling" ,
      "--profile-port", "7777",
      "--dapr-grpc-port", "50002",
      "--components-path", "/components",
      "--config", "/configuration/config.yaml"
    ]
    volumes:
      # Volume mounts are relative from the root directory where podman-compose is run from
      - "./dapr/components/:/components"
      - "./dapr/config/:/configuration"
    depends_on:
      - webapp
    network_mode: "service:webapp"

networks:
    demo-dapr-network:
      driver: bridge
