version: '3.7'
name: demo

services:
  backend-spring-migrations:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URI: jdbc:postgresql://postgres:5432/postgres-spring
      # DB_DEBUG: 1
      # DB_SSL: postgres # Production
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
