version: '3.7'
name: demo

services:
  ############################
  # backend app + Dapr sidecar
  ############################
  backend-spring:
    labels:
      - "sos.service-type=microservice"
    build:
      context: ./app/backend-spring
      dockerfile: ./Dockerfile.dev
    ports:
      - "3004:3004"
    environment:
      # SEED_DATA: true # Load seed data on start
      DAPR_HOST: 127.0.0.1
      DAPR_PORT: 3500
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 3004
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_URI: jdbc:postgresql://postgres:5432/postgres-spring
      OTEL_ENDPOINT: http://grafana-otel:4318
      OTEL_METRICS_URL: http://grafana-otel:4318/v1/metrics
      # DB_DEBUG: 1
      # DB_SSL: postgres # Production
    volumes:
      - ./app/backend-spring/src:/app/src
    depends_on:
      - redis
      - placement
      - zipkin
      - postgres
    restart: on-failure:3
    networks:
      - dapr-net
  backend-spring-dapr:
    labels:
      - "sos.service-type=microservice"
      - "dapr.io/enabled=true"  # Enable Dapr for this service
      - "dapr.io/config=configstore"
    image: "docker.io/daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "backend-spring",
      "--app-port", "3004",
      "--config", "/configuration/config.yaml",
      "--dapr-http-port", "3500",
      "--enable-api-logging",
      "--enable-profiling",
      "--log-as-json", "true",
      "--placement-host-address", "placement:50005",
      "--profile-port", "7777",
      "--resources-path", "/components"
      ]
    volumes:
      # Volume mounts are relative from the root directory where dapr-net-compose is run from
      - "./shared/dapr/dapr/components/:/components"
      - "./shared/dapr/dapr/config/:/configuration"
    depends_on:
      - backend-spring
      - placement
    network_mode: "service:backend-spring"

networks:
  dapr-net: # here we set the network name
    driver: bridge
