version: '3.7'
name: demo

services:
  backend-flask:
    command: "flask --app src/app run -h 0.0.0.0 -p 3003"
    environment:
      DEBUGGER: "true"
      DEBUGGER_PORT: 9229
    ports:
      - "3003:3003"
      - "9229:9229"
    volumes:
      - ./app/backend-flask/migrations:/app/migrations
