version: '3.7'
name: demo

services:
  ############################
  # backend app + Dapr sidecar
  ############################
  backend-flask:
    build:
      context: ./app/backend-flask
      dockerfile: ./Dockerfile.dev
    ports:
      - "3003:3003"
    command: "opentelemetry-instrument flask --app src/app run -h 0.0.0.0 -p 3003"
    environment:
      # SEED_DATA: true # Load seed data on start
      DAPR_HOST: 127.0.0.1
      DAPR_PORT: 3500
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 3003
      DB_URI: "postgresql+psycopg://postgres:postgres@postgres:5432/postgres-flask"
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_EXPORTER_OTLP_ENDPOINT: http://grafana-otel:4318/
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: backend-flask
      OTEL_TRACES_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      # DB_DEBUG: 1
      # DB_SSL: postgres # Production
    volumes:
      - /app/__pycache__ # Persist docker containers modules so that localhost are not used
      - ./app/backend-flask/src:/app/src
      - ./app/backend-flask/migrations:/app/migrations
    depends_on:
      - redis
      - placement
      - zipkin
      - postgres
    restart: on-failure:3
    networks:
      - dapr-net
  backend-flask-dapr:
    image: "docker.io/daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "backend-flask",
      "--app-port", "3003",
      "--config", "/configuration/config.yaml",
      "--dapr-http-port", "3500",
      "--enable-api-logging",
      "--enable-profiling",
      "--log-as-json", "true",
      "--placement-host-address", "placement:50006",
      "--profile-port", "7777",
      "--resources-path", "/components"
      ]
    volumes:
      # Volume mounts are relative from the root directory where dapr-net-compose is run from
      - "./dapr/components/:/components"
      - "./dapr/config/:/configuration"
    depends_on:
      - backend-flask
    labels:
      - "dapr.io/enabled=true"  # Enable Dapr for this service
      - "dapr.io/config=configstore"
    network_mode: "service:backend-flask"

networks:
  dapr-net: # here we set the network name
    driver: bridge
