version: '3.7'
name: demo

services:
  backend-flask:
    command: "flask --app src/app run -h 0.0.0.0 -p 3003 --extra-files src/ --debug"
    ports:
      - "3003:3003"
    volumes:
      - ./app/backend-flask/migrations:/app/migrations
