version: '3.7'

name: demo

services:
  # Shared db
  postgres:
    image: "docker.io/postgres:17-alpine"
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      DB_NAMES: postgres-ts,postgres-dotnet,postgres-flask
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
    networks:
      - dapr-net

volumes:
  db-data:

networks:
  dapr-net: # here we set the network name
    driver: bridge
