version: '3.7'
name: demo

services:
  backend-dotnet-migrations:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    entrypoint: ["dotnet", "run", "--migrate"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      # Aspnet connectionstrings environment variable convention
      ConnectionStrings__Postgres: "Server=postgres;Port=5432;User Id=postgres;Password=postgres;Database=postgres-dotnet;"
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
