version: '3.7'
services:
  ############################
  # backend app + Dapr sidecar
  ############################
  backend-dotnet:
    build:
      context: ./app/backend-dotnet
      dockerfile: ./Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:3002"
      DAPR_HOST: 127.0.0.1
      DAPR_PORT: 3500
      # Aspnet connectionstrings environment variable convention
      ConnectionStrings__Postgres: "Server=postgres;Port=5432;User Id=postgres;Password=postgres;Database=postgres;"
      # DB_DEBUG: 1
      # DB_SSL: postgres # Production
    volumes:
      - ./app/backend-dotnet/src:/App/src # Mount localhost source to support hot reload
    depends_on:
      - redis
      - placement
      - zipkin
      - postgres
    restart: on-failure:3
    networks:
      - dapr-net
  backend-dotnet-dapr:
    image: "docker.io/daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "backend-dotnet",
      "--app-port", "3002",
      "--config", "/configuration/config.yaml",
      "--dapr-http-port", "3500",
      "--enable-api-logging",
      "--enable-profiling",
      "--log-as-json", "true",
      "--placement-host-address", "placement:50006",
      "--profile-port", "7777",
      "--resources-path", "/components"
      ]
    volumes:
      # Volume mounts are relative from the root directory where dapr-net-compose is run from
      - "./dapr/components/:/components"
      - "./dapr/config/:/configuration"
    depends_on:
      - backend-dotnet
    labels:
      - "dapr.io/enabled=true"  # Enable Dapr for this service
      - "dapr.io/config=configstore"
    network_mode: "service:backend-dotnet"

networks:
  dapr-net: # here we set the network name
    driver: bridge
