spring:
  main:
    banner-mode: none
  datasource:
    url: ${DB_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
otel:
  exporter:
    otlp:
      endpoint:${OTEL_ENDPOINT}
management:
  tracing:
    sampling:
      probability: 0.1
  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS_URL}
